package ru.spb.ipo.generator.chess;

public class ChessStringGeneration {

    public static String AnswerExp1;

    public static String Starter() {
        StringBuffer sb = new StringBuffer();

        sb.append("<sourceSet>\n"
                + "<set length=\"${rook}\" type=\"CombinationSet\">\n"
                + "<set type=\"DecartSet\">\n"
                + "<set first=\"1\" last=\"${n}\" type=\"NumericSet\"/>\n"
                + "<set first=\"1\" last=\"${m}\" type=\"NumericSet\"/>\n"
                + "</set>\n"
                + "</set>\n"
                + "</sourceSet>\n"
                + "<verifier type=\"SimpleVerifier\">\n"
                + "<function type=\"And\">\n"
                + "<function type=\"Equals\">\n"
                + "<function type=\"Add\">\n"
                + "<for first=\"1\" inc=\"1\" last=\"${rook}\" name=\"i\">\n"
                + "<function type=\"And\">\n"
                + "<function type=\"Equals\">\n"
                + "<function type=\"Add\">\n"
                + "<for first=\"1\" inc=\"1\" last=\"${rook}\" name=\"j\">"
                + "<function type=\"And\">");
        return sb.toString();
    }

    public static String Footer(int rookM) {
        StringBuffer sb = new StringBuffer();
        sb.append("</function>\n"
                + "</for>\n"
                + "</function>\n"
                + "<constElement>" + rookM + "</constElement>\n"
                + "</function>\n"
                + "</function>\n"
                + "</for>\n"
                + "</function>\n"
                + "<constElement>" + ChessFuncPanel.numberFigur + "</constElement>\n"
                + "</function>\n"
                + "</function>\n"
                + "</verifier>");
        return sb.toString();
    }

    public static String Ladya() {
        StringBuffer sb = new StringBuffer();
        if (ChessFuncPanel.isKill) {
            sb.append("<function type=\"Or\">\n"
                    + "\n"
                    + "<function type=\"Equals\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "\n"
                    + "<function type=\"Equals\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "\n"
                    + "</function>");
        } else {
            sb.append("<function type=\"Not\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Not\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
        }
        return sb.toString();
    }

    public static String Ferz() {
        if (ChessFuncPanel.isKill) {
            StringBuffer sb = new StringBuffer();
            sb.append("<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Add\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Add\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
            return sb.toString();
        } else {
            return Slon() + Ladya();
        }
    }

    public static String Koni() {
        StringBuffer sb = new StringBuffer();
        if (ChessFuncPanel.isKill) {
            sb.append("<function type=\"Or\">\n"
                    + "\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>3</constElement>\n"
                    + "</function>\n"
                    + "\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-3</constElement>\n"
                    + "</function>\n"
                    + "\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "\n"
                    + "</function>");
        } else {
            sb.append("<function type=\"Not\"> \n"
                    + "<function type=\"Equals\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<constElement>1</constElement> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Not\"> \n"
                    + "<function type=\"Equals\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<constElement>3</constElement> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Not\"> \n"
                    + "<function type=\"Equals\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<constElement>-3</constElement> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Not\"> \n"
                    + "<function type=\"Equals\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${j}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function type=\"Sub\"> \n"
                    + "<function axis=\"1\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<function axis=\"2\" type=\"Projection\"> \n"
                    + "<function axis=\"${i}\" type=\"Projection\"> \n"
                    + "<current-set-element/> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "</function> \n"
                    + "<constElement>-1</constElement> \n"
                    + "</function> \n"
                    + "</function>");
        }

        return sb.toString();
    }

    public static String Korol() {
        StringBuffer sb = new StringBuffer();
        if (ChessFuncPanel.isKill) {
            sb.append("<function type=\"And\">\n"
                    + "\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>0</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>0</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
        } else {
            sb.append("<function type=\"Not\">\n"
                    + "<function type=\"And\">\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>0</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>0</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
        }

        return sb.toString();
    }

    public static String Pesh() {
        StringBuffer sb = new StringBuffer();
        if (ChessFuncPanel.isKill) {
            sb.append("<function type=\"And\">\n"
                    + "\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "\n"
                    + "</function>");
        } else {
            sb.append("<function type=\"Not\">\n"
                    + "<function type=\"And\">\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>1</constElement>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<constElement>-1</constElement>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
        }
        return sb.toString();
    }

    public static String Slon() {
        StringBuffer sb = new StringBuffer();
        if (ChessFuncPanel.isKill) {
            sb.append("<function type=\"Or\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Add\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Add\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
        } else {
            sb.append("<function type=\"Not\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Sub\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Not\">\n"
                    + "<function type=\"Equals\">\n"
                    + "<function type=\"Add\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${i}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function type=\"Add\">\n"
                    + "<function axis=\"1\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "<function axis=\"2\" type=\"Projection\">\n"
                    + "<function axis=\"${j}\" type=\"Projection\">\n"
                    + "<current-set-element/>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>\n"
                    + "</function>");
        }
        return sb.toString();
    }

    public static String PobDiag(int n) {
        StringBuffer sb = new StringBuffer();

        sb.append("<function type=\"Not\">\n"
                + "<function type=\"Equals\">\n"
                + "<function type=\"Add\">\n"
                + "<function axis=\"1\" type=\"Projection\">\n"
                + "<function axis=\"${i}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "<function axis=\"2\" type=\"Projection\">\n"
                + "<function axis=\"${i}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "</function>\n"
                + "<constElement>" + (n + 1) + "</constElement>\n"
                + "</function>\n"
                + "</function>\n"
                + "<function type=\"Not\">\n"
                + "<function type=\"Equals\">\n"
                + "<function type=\"Add\">\n"
                + "<function axis=\"1\" type=\"Projection\">\n"
                + "<function axis=\"${j}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "<function axis=\"2\" type=\"Projection\">\n"
                + "<function axis=\"${j}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "</function>\n"
                + "<constElement>" + (n + 1) + "</constElement>\n"
                + "</function>\n"
                + "</function>\n");
        return sb.toString();
    }

    public static String Diag() {
        StringBuffer sb = new StringBuffer();
        sb.append("<function type=\"Not\">\n"
                + "<function type=\"Equals\">\n"
                + "<function axis=\"1\" type=\"Projection\">\n"
                + "<function axis=\"${i}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "<function axis=\"2\" type=\"Projection\">\n"
                + "<function axis=\"${i}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "</function>\n"
                + "</function>\n"
                + "<function type=\"Not\">\n"
                + "<function type=\"Equals\">\n"
                + "<function axis=\"1\" type=\"Projection\">\n"
                + "<function axis=\"${j}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "<function axis=\"2\" type=\"Projection\">\n"
                + "<function axis=\"${j}\" type=\"Projection\">\n"
                + "<current-set-element/>\n"
                + "</function>\n"
                + "</function>\n"
                + "</function>\n"
                + "</function>\n"
        );
        return sb.toString();
    }

    public static String Factorial(int length) {
        StringBuffer sb = new StringBuffer();
        sb.append("1");
        for (int i = 1; i < length; i++) {
            sb.append("*" + i);
        }
        return sb.toString();
    }

    public static String sochet(int n1, int m1) {
        StringBuffer sb = new StringBuffer();
        sb.append(Factorial(n1));
        sb.append("/(");
        sb.append(Factorial(m1));
        sb.append("*");
        sb.append(Factorial(n1 - m1));
        sb.append(")");
        return sb.toString();
    }

    public static String stepen2(int n1) {
        StringBuffer sb = new StringBuffer();
        sb.append("2");
        for (int i = 1; i < n1; i++) {
            sb.append("*2");
        }
        return sb.toString();
    }

    public static String stepen1(int n1, int step) {
        StringBuffer sb = new StringBuffer();
        int k = n1;
        for (int i = 0; i < step; i++) {
            k = k * n1;
        }
        sb.append("(" + k + ")");
        return sb.toString();
    }

    public static String getAnswerExp1(int n) {
        StringBuffer sb = new StringBuffer();
        if (n == 1) {
            sb.append("1");
        } else {
            sb.append(stepen2(n));
        }
        return sb.toString();
    }

    public static String getAnswerExp2(int n) {
        StringBuffer sb = new StringBuffer();
        if (n % 2 == 0) {
            sb.append(n + "*" + n + "/2");
        } else {
            sb.append("(1+" + n + ")*(1+" + n + ")/2");
        }
        return sb.toString();
    }

    public static String getAnswerExp3(int n, int m) {
        StringBuffer sb = new StringBuffer();

        sb.append("(");
        sb.append(Factorial(ChessFuncPanel.numberFigur));
        sb.append("*");
        sb.append(")*(");
        sb.append(sochet(n, ChessFuncPanel.numberFigur));
        sb.append(")*(");
        sb.append(sochet(m, ChessFuncPanel.numberFigur));
        sb.append(")");

        return sb.toString();
    }

    public static String getAnswerExp4(int n) {
        StringBuffer sb = new StringBuffer();
        sb.append("0");
        for (int i = 0; i < ChessFuncPanel.numberFigur; i++) {
            sb.append("+");
            sb.append(stepen1(-1, i) + "*");
            sb.append(sochet(n, i));
            sb.append("*(");
            sb.append(Factorial(ChessFuncPanel.numberFigur - i));
            sb.append("*");
            sb.append(")*(");
            sb.append(sochet(n - i, ChessFuncPanel.numberFigur - i));
            sb.append(")*(");
            sb.append(sochet(n - i, ChessFuncPanel.numberFigur - i));
            sb.append(")");
        }
        return sb.toString();
    }
}
